version: "3.8"

services:
  react_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - react_build:/app/dist
    restart: "no"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - react_app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/ssl/certs:ro
      - react_build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  react_build:
